project_name: attiny-controller

release:
  github:
    owner: TheCacophonyProject
    name: attiny-controller
  name_template: '{{.Tag}}'

builds:
- goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
  main: .
  ldflags: -s -w -X main.version={{.Version}}
  binary: attiny-controller

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Controls the ATtiny on the Pi Hat
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  contents:
    - src: _release/attiny-controller.service
      dst: /etc/systemd/system/attiny-controller.service
    - src: _release/org.cacophony.ATtiny.conf
      dst: /etc/dbus-1/system.d/org.cacophony.ATtiny.conf
    - src: _release/stay-on-for
      dst: /usr/bin/stay-on-for
    - src: _release/10-notify-attiny
      dst: /lib/dhcpcd/dhcpcd-hooks/10-notify-attiny
  scripts:
    postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
